<a href="https://colab.research.google.com/github/Anonymouskau/StudentPefrormance/blob/main/StudentPerformance_index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("nikhil7280/student-performance-multiple-linear-regression")

print("Path to dataset files:", path)

Path to dataset files: /root/.cache/kagglehub/datasets/nikhil7280/student-performance-multiple-linear-regression/versions/1


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

In [ ]:
df = pd.read_csv(path + "/Student_Performance.csv")
df.head()
X=df.drop('Performance Index',axis=1)
y=df[['Performance Index']]
X['Extracurricular Activities']=X['Extracurricular Activities'].map({'Yes':1,"No":0})

X

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0                 7               99                           1            9   
1                 4               82                           0            4   
2                 8               51                           1            7   
3                 5               52                           1            5   
4                 7               75                           0            8   
...             ...              ...                         ...          ...   
9995              1               49                           1            4   
9996              7               64                           1            8   
9997              6               83                           1            8   
9998              9               97                           1            7   
9999              7               74                           0            8   

      Sample Question Papers Practiced  
0                                    1  
1                                    2  
2                                    2  
3                                    2  
4                                    5  
...                                ...  
9995                                 2  
9996                                 5  
9997                                 5  
9998                                 0  
9999                                 1  

[10000 rows x 5 columns]

In [ ]:
head_values=list(X.columns)
for i in head_values:
  print( X[f"{i}"].unique())
  print( X[f"{i}"].isna().sum())

[7 4 8 5 3 6 2 1 9]
0
[99 82 51 52 75 78 73 45 77 89 91 79 47 72 83 54 96 74 85 61 62 84 94 90
 44 70 67 97 59 55 68 63 46 76 43 81 93 98 48 92 64 88 60 87 40 69 80 95
 49 50 53 71 56 58 66 65 57 41 42 86]
0
[1 0]
0
[9 4 7 5 8 6]
0
[1 2 5 6 0 8 3 4 9 7]
0


# prompt: indexing dataframe

print(df.iloc[0])
print(df.loc[0])
print(df.iloc[0:5])
print(df['Hours Studied'].iloc[0:5])
print(df[['Hours Studied', 'Previous Scores']].iloc[0:5])


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
y_train = scaler.fit_transform(y_train)
y_test = scaler.transform(y_test)





array([[-0.22454725],
       [-1.83905839],
       [-0.48495227],
       ...,
       [-2.04738241],
       [ 0.50458681],
       [-0.43287127]])

In [ ]:
from sklearn.linear_model import LinearRegression


mlr=LinearRegression()
mlr.fit(X_train,y_train)

mlr_Score=math.floor(mlr.score(X_test,y_test)*100)
print(mlr_Score)


Case_1=X.iloc[100]




98


In [ ]:
mlr.predict([Case_1])

array([[47.41]])